spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5433/demo
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

app:
  cleanup-cron: "*/10 * * * * *"