openapi: 3.0.1
info:
  title: Name API
  version: 1.0.0
paths:
  /names:
    get:
      summary: Получить список имён
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Добавить имя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: Имя добавлено
          content:
            text/plain:
              schema:
                type: string
  
